// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4BTflCfs8sva28dnd5JiDBbZy4hvJJz8',
    appId: '1:856647999156:web:efe58c012cd7a7bbbf01e1',
    messagingSenderId: '856647999156',
    projectId: 'hire-me-sql-6d7b5',
    authDomain: 'hire-me-sql-6d7b5.firebaseapp.com',
    storageBucket: 'hire-me-sql-6d7b5.firebasestorage.app',
    measurementId: 'G-2B2Y4XDH7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBykfrWhrzH2PFo2nuaRIwqf_NYoZHscZs',
    appId: '1:856647999156:android:78332b8b07d271f5bf01e1',
    messagingSenderId: '856647999156',
    projectId: 'hire-me-sql-6d7b5',
    storageBucket: 'hire-me-sql-6d7b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDex1dDEc1sMK65ecYM-ogHc39VZF2xDOA',
    appId: '1:856647999156:ios:f708d1c1020521bebf01e1',
    messagingSenderId: '856647999156',
    projectId: 'hire-me-sql-6d7b5',
    storageBucket: 'hire-me-sql-6d7b5.firebasestorage.app',
    iosBundleId: 'com.example.hireMeSql',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDex1dDEc1sMK65ecYM-ogHc39VZF2xDOA',
    appId: '1:856647999156:ios:f708d1c1020521bebf01e1',
    messagingSenderId: '856647999156',
    projectId: 'hire-me-sql-6d7b5',
    storageBucket: 'hire-me-sql-6d7b5.firebasestorage.app',
    iosBundleId: 'com.example.hireMeSql',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4BTflCfs8sva28dnd5JiDBbZy4hvJJz8',
    appId: '1:856647999156:web:d68d5239b1e24842bf01e1',
    messagingSenderId: '856647999156',
    projectId: 'hire-me-sql-6d7b5',
    authDomain: 'hire-me-sql-6d7b5.firebaseapp.com',
    storageBucket: 'hire-me-sql-6d7b5.firebasestorage.app',
    measurementId: 'G-YVEP5RJMKF',
  );
}
